defaults:
  - _self_

seed: 42
iterations: 20
dataset: cifar10
antennas_transmitter: 4
antennas_receiver: 4
base_station_model: vit_tiny_patch16_224
agents_models:
  - vit_small_patch16_224
  - vit_small_patch32_224
  - vit_base_patch16_224
rho: 1e2
px_cost: 1.0
snr: 20.0
device: cpu
